### ISSUE TITLE
TypeError: (0, paddedBits_1.bitsToPaddedBuffer)(bits).copy is not a function (it is undefined

### ISSUE THREAD

**Issue by divyangkhatri** [ton-org/ton-core#40]
Hello,
Version Details
react-native: 0.75.1
"@ton/core": "^0.56.3",
"@ton/crypto": "^3.3.0",
"@ton/ton": "^14.0.0",

When i just import the @ton/ton package, I am facing this error "TypeError: (0, paddedBits_1.bitsToPaddedBuffer)(bits).copy is not a function (it is undefined" after updating the react-native version. 0.72.7 to 0.75.1. 
Previously it was working fine in older version of RN.
On the below line there is the crash
https://github.com/ton-org/ton-core/blob/b5aa9381ae266185492f0c769056224d8b99d788/src/boc/cell/descriptor.ts#L35
I also attach the screenshot of the error
 
 <img src="https://github.com/user-attachments/assets/bae8220e-8621-44c9-b576-b9b39c8b51b0" width="500" height="1200" >

**Comment by joon08** [comment]
Have you solved this problem?

**Comment by verytactical** [comment]
This seems to be an issue with incorrect implementation of Buffer in React Native.

We plan to get rid of uses of Buffer in 1.0.
